# Generated by Django 3.0.4 on 2020-03-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='slug',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='slug',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='statemodel',
            name='slug',
            field=models.CharField(default='', max_length=70),
        ),
    ]
