# Generated by Django 3.0.4 on 2020-03-27 08:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0002_auto_20200326_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCasesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.CharField(default='', max_length=70)),
                ('total_cases', models.IntegerField(blank=True, null=True)),
                ('total_deaths', models.IntegerField(blank=True, null=True)),
                ('total_recovers', models.IntegerField(blank=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_of_city', to='appdata.StateModel')),
            ],
            options={
                'db_table': 'city_cases',
            },
        ),
        migrations.DeleteModel(
            name='CityModel',
        ),
    ]
