# Generated by Django 3.0.4 on 2020-03-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0003_auto_20200327_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='statemodel',
            name='total_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statemodel',
            name='total_deaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statemodel',
            name='total_recovers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
