# Generated by Django 3.0.4 on 2020-03-30 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0004_auto_20200330_0515'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StateModel',
            new_name='StateCasesModel',
        ),
    ]
