# Generated by Django 3.0.4 on 2020-03-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0005_auto_20200330_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrymodel',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
