# Generated by Django 3.0.4 on 2020-04-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0006_countrymodel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='statecasesmodel',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='statecasesmodel',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='statecasesmodel',
            name='population',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
