# Generated by Django 3.0.4 on 2020-04-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0007_auto_20200401_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='statecasesmodel',
            name='sick',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
