# Generated by Django 3.0.4 on 2020-03-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportmodel',
            old_name='failed_reason',
            new_name='status_msg',
        ),
    ]
